/*
 * JPhyloIO - Event based parsing and stream writing of multiple sequence alignment and tree formats. 
 * Copyright (C) 2015-2016  Ben Stöver, Sarah Wiechers
 * <http://bioinfweb.info/JPhyloIO>
 * 
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package info.bioinfweb.jphyloio.formats.pde;


import static info.bioinfweb.jphyloio.test.JPhyloIOTestTools.*;
import static org.junit.Assert.*;

import info.bioinfweb.commons.bio.CharacterStateSetType;
import info.bioinfweb.commons.io.W3CXSConstants;
import info.bioinfweb.jphyloio.ReadWriteConstants;
import info.bioinfweb.jphyloio.ReadWriteParameterMap;
import info.bioinfweb.jphyloio.events.meta.LiteralContentSequenceType;
import info.bioinfweb.jphyloio.events.meta.URIOrStringIdentifier;
import info.bioinfweb.jphyloio.events.type.EventContentType;
import info.bioinfweb.jphyloio.events.type.EventTopologyType;
import info.bioinfweb.jphyloio.exception.JPhyloIOReaderException;
import info.bioinfweb.jphyloio.test.JPhyloIOTestTools;

import java.awt.Color;
import java.io.File;
import java.net.URI;

import org.junit.Test;



public class PDEEventReaderTest implements PDEConstants {
	
	
	@Test
	public void readDNASequences() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/SimpleDNASeq.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
								
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACGTCGCTCGAG-CTGATCG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("CACGGTG--CTAGCAGATCG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, "some sequence", true, reader);
				assertCharactersEvent("TT-ACGATGAATTGCTGGCA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readNoAlignment() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingMatrix.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				assertLabeledIDEvent(EventContentType.OTU, null, "A", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertLabeledIDEvent(EventContentType.OTU, null, "B", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertLabeledIDEvent(EventContentType.OTU, null, "C", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 23, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readNoHeader() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingHeader.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, null, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, null, null, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, null, null, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, null, null, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readMissingSequenceInfo() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingSequenceInfo.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
								
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, null, null, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, null, null, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readNoAlignmentAndNoHeader() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingHeaderAndAlignment.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readMissingSequenceEndToken() throws Exception {
		PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingEndToken.pde"), new ReadWriteParameterMap());
		try {
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				assertLabeledIDEvent(EventContentType.OTU, null, "C", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertLabeledIDEvent(EventContentType.OTU, null, "B", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertLabeledIDEvent(EventContentType.OTU, null, "A", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, "seq0", "C", "otu0", reader);
				
				fail("Exception not thrown");
			}
			catch (JPhyloIOReaderException e) {
				assertEquals(e.getMessage(), "The sequence with the index \"0\" was found to be longer"
											+ " than the specified alignment length of 20. This is not allowed in PDE files.");
			}
		}
		finally {
			reader.close();
		}		
	}
	
	
	@Test
	public void readUnequalSequenceLength() throws Exception {
		PDEEventReader reader = new PDEEventReader(new File("data/PDE/UnequalSequenceLength.pde"), new ReadWriteParameterMap());
		try {
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertLabeledIDEvent(EventContentType.OTU, null, "A", reader);
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACGTCGCTCGAG-CTGATCG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				
				fail("Exception not thrown");
			}
			catch (JPhyloIOReaderException e) {
				assertEquals(e.getMessage(), "The sequence with the index \"1\" was found to be shorter"
						+ " than the specified alignment length of 20. This is not allowed in PDE files.");
			}
		}
		finally {
			reader.close();
		}		
	}
	
	
	@Test
	public void readMissingMetaDefinitions() throws Exception {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/MissingMetaDefinition.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 23, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "23", null, 23, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon1, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, 
						"some sequence", true, reader);	
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), new URI("someFile.scf"), null, true, reader);
				assertCharactersEvent("ACTGACTGAC---TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), new URI("someFile.scf"), null, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_ACCESS_NUMBER), new URIOrStringIdentifier(META_TYPE_NUMBER, null), "45", null, "45", true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some comment", null, 
						"some comment", true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier("testNumber", ReadWriteConstants.PREDICATE_HAS_LITERAL_METADATA), new URIOrStringIdentifier(META_TYPE_NUMBER, null), 
						"18", null, 18.0, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier("33", ReadWriteConstants.PREDICATE_HAS_LITERAL_METADATA), null, "some String", null, "some String", true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier("34", ReadWriteConstants.PREDICATE_HAS_LITERAL_METADATA), null, "someFile.txt", null, "someFile.txt", true, reader);
				assertCharactersEvent("ACTGACTGACAACTGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon3, reader);
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), new File("\\\\nwz.wwu.de\\dfs\\home\\s\\s_wiec03\\Desktop\\sample.scf").toURI(), null, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some comment", null, "some comment", true, reader);				
				assertCharactersEvent("ACTGACTGAC---TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readLabeledAlignment() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/Label.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACGTCGCTCGAG-CTGATCG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("CACGGTG--CTAGCAGATCG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, "some sequence", true, reader);
				assertCharactersEvent("TT-ACGATGAATTGCTGGCA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readTaxonSet() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/TaxonSet.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, "some sequence", true, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readCharSets() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/SimpleCharSet.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				String alignment = assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.CHARACTER_SET, null, "charSet1", alignment, reader);				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_CHARSET_VISIBILITY), new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_BOOLEAN), 
						"true", null, true, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_CHARSET_COLOR), null, "FC3D33", null, Color.decode("#FC3D33"), true, reader);
				assertCharacterSetIntervalEvent(1, 2, reader);
				assertCharacterSetIntervalEvent(3, 14, reader);
				assertCharacterSetIntervalEvent(15, 18, reader);
				assertCharacterSetIntervalEvent(19, 20, reader);
				assertPartEndEvent(EventContentType.CHARACTER_SET, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.CHARACTER_SET, null, "charSet2", alignment, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_CHARSET_VISIBILITY), new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_BOOLEAN), 
						"false", null, false, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_CHARSET_COLOR), null, "FFFF33", null, Color.decode("#FFFF33"), true, reader);				
				assertCharacterSetIntervalEvent(4, 9, reader);
				assertCharacterSetIntervalEvent(10, 11, reader);
				assertCharacterSetIntervalEvent(12, 20, reader);
				assertPartEndEvent(EventContentType.CHARACTER_SET, true, reader);				
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, 
						"some sequence", true, reader);
				assertCharactersEvent("ACTGACTGACTGTGACCATA", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readProteinSequences() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/SimpleProteinSeq.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 20, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "20", null, 20, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ATWSATWSATWSATWSATWS", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("ATWSATWSATWSATWSATWS", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, 
						"some sequence", true, reader);
				assertCharactersEvent("ATWSATWSATWSATWSATWS", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readSequencesWithCustomMeta() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/customMetaDNASeq.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 23, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "23", null, 23, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon1, reader);				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, 
						"some sequence", true, reader);	
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), new URI("someFile.scf"), null, true, reader);
				assertCharactersEvent("ACTGACTGAC---TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), new URI("someFile.scf"), null, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_ACCESS_NUMBER), new URIOrStringIdentifier(META_TYPE_NUMBER, null), "45", null, "45", true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some comment", null, 
						"some comment", true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier("testNumber", ReadWriteConstants.PREDICATE_HAS_LITERAL_METADATA), new URIOrStringIdentifier(META_TYPE_NUMBER, null), 
						"18", null, 18.0, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier("testString", ReadWriteConstants.PREDICATE_HAS_LITERAL_METADATA), new URIOrStringIdentifier(META_TYPE_STRING, null), 
						"some String", null, "some String", true, reader);
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier("testFile", ReadWriteConstants.PREDICATE_HAS_RESOURCE_METADATA), new URI("someFile.txt"), null, 
						true, reader);
				assertCharactersEvent("ACTGACTGACAACTGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon3, reader);
				JPhyloIOTestTools.assertResourceMetaEvent(new URIOrStringIdentifier(null, PREDICATE_LINKED_FILE), 
						new File("\\\\nwz.wwu.de\\dfs\\home\\s\\s_wiec03\\Desktop\\sample.scf").toURI(), null, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some comment", null, 
						"some comment", true, reader);				
				assertCharactersEvent("ACTGACTGAC---TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readSequenceWithMatchTokens() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/DNASeqMatchToken.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 23, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "23", null, 23, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("ACTGACTGAC-A-TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("ACTGACTGACAACTGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, "some sequence", true, reader);
				assertCharactersEvent("ACTGACTGAC---TGACTGACTG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
				
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
	
	
	@Test
	public void readSequenceWithUnknownTokens() {
		try {
			PDEEventReader reader = new PDEEventReader(new File("data/PDE/DNASeqMissingToken.pde"), new ReadWriteParameterMap());
			try {
				assertEventType(EventContentType.DOCUMENT, EventTopologyType.START, reader);
				
				assertCommentEventRegExp(" Generated by PhyDE \\d.\\d+\\n\\D+\\s\\D+\\s\\d+\\s\\d+:\\d+:\\d+\\s\\D+\\s\\d+\\s+", reader);
				
				assertLiteralMetaStartEvent(new URIOrStringIdentifier(null, PREDICATE_DESCRIPTION), LiteralContentSequenceType.SIMPLE, 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_STRING), null, reader);
				assertEndEvent(EventContentType.LITERAL_META, reader);
				
				String taxonList = assertLabeledIDEvent(EventContentType.OTU_LIST, null, null, reader).getID();
				String taxon1 = assertLabeledIDEvent(EventContentType.OTU, null, "C", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon2 = assertLabeledIDEvent(EventContentType.OTU, null, "B", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				String taxon3 = assertLabeledIDEvent(EventContentType.OTU, null, "A", reader).getID();
				assertEndEvent(EventContentType.OTU, reader);
				assertEndEvent(EventContentType.OTU_LIST, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.ALIGNMENT, null, null, taxonList, reader);
				
				assertTokenSetDefinitionEvent(CharacterStateSetType.DNA, null, reader);
				assertCharacterSetIntervalEvent(0, 25, reader);
				assertEndEvent(EventContentType.TOKEN_SET_DEFINITION, reader);
				
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_CHARACTER_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "25", null, 25, true, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, ReadWriteConstants.PREDICATE_SEQUENCE_COUNT), 
						new URIOrStringIdentifier(null, W3CXSConstants.DATA_TYPE_INT), "3", null, 3, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "C", taxon1, reader);
				assertCharactersEvent("AAAAGTGATAA-CTTTCAAATTCAG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "B", taxon2, reader);
				assertCharactersEvent("????????????CTTTCAAATTCAG", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertLinkedLabeledIDEvent(EventContentType.SEQUENCE, null, "A", taxon3, reader);
				assertLiteralMetaEvent(new URIOrStringIdentifier(null, PREDICATE_COMMENT), new URIOrStringIdentifier(META_TYPE_STRING, null), "some sequence", null, "some sequence", true, reader);
				assertCharactersEvent("AAAAGTGATAACTT???????????", false, reader);
				assertPartEndEvent(EventContentType.SEQUENCE, true, reader);
				
				assertEndEvent(EventContentType.ALIGNMENT, reader);
				assertEndEvent(EventContentType.DOCUMENT, reader);
	
				assertFalse(reader.hasNextEvent());
			}
			finally {
				reader.close();
			}
		}
		catch (Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
}
