<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Tue Feb 23 14:01:51 CET 2016  -->
<phyde id="JgfyFmbkEeGK3HRf" version="0.994">
	<description></description>
	<alignment datatype="dna" width="870" height="3" gencode="0" offset="-1">
		<header>
			<entries>
				32 "testNumber" NUMBER
				33 "testFile" FILE
				34 "testString" STRING
			</entries>
			<seq idx="0" cs1="883877" >
				<e id="1">593_cp4243-cp42</e>
				<e id="2">593_cp4243-cp42.scf</e>
			</seq>
			<seq idx="1" cs1="26070374" >
				<e id="1">593_cp4243-cp43</e>
				<e id="2">593_cp4243-cp43.scf</e>
				<e id="32">18</e>
				<e id="33">someFile.txt</e>
				<e id="34">some String</e>
				<e id="3">45</e>
				<e id="4">some Comment</e>
			</seq>
			<seq idx="2" cs1="885853" >
				<e id="1">Melampyrum nemorosum (593 Con) SE</e>
				<e id="4">Consensus: 593_cp4243_42 + 593_cp4243_cp43</e>
			</seq>
		</header>
		<matrix>
			<block x="0" y="0" width="870" height="3">
			\FE53:
			TTTTGGAAaaGGAAGGGATATTGGACAGCGGTAAAAGCGTTTTCTTTAGGTAAATCCCTGTCTACTGGAAATTCAAAAAGTTTTTTGAGCGACAAACAAATAAAATAAGTAAAAAAAATCTTAAAACATAACATGCTGGAATAAGCTAATATAGGCCCGACTCGCTTTTGGAGTAATTTCAGATCAAAAATCCAATTCTCGAATTCCATTTCCTAGTGAGTAACTCAATAGGAAATGGAATTCGTTCTACTATAATAGAATAGAACTTAGAATCAGAATTTTTCTATATTCACTTTCCGCATTAAAAAATTAAGAAACTTTCGTCTTGTTGACAAAAAAAGCAAGATACTCAATTTTTTTTAGTATATTTACGAAATTTACAAGGCGAGGAGTATTATTTTCTCCATCAACCTATTTTATTTGGGATAGACTATAAATTTTATTTTTTGTACAACTTTCTTTCTTTTCTAACCTCGTACCTCGTATATATCAGCATCAATCCACGCAAA
			AAGACTTAGTTAAGATGTTTTCAAATATGTCGAAATTTTGAATGATTCAAAATAGGTTCTTTTTTCAATGATTTTTGTTTCTCTTTTTGAAATCAAATAAATCAAAAACGATTCATTAAAAAAAAAATAAAAAATACACAATAAAACTACGACCCTAGCTTCAAATTCAAATAATGAACCCTCAAATACCTAAGTTGAATGAATTTTTATTTTTGATTCATGAATTTGACTTTTTCCTAAAAAATATTACACCCAATTTCATTCTTAAATCTAGACGGTTGCTTATTCATAGGCTATTATGAATTCAAGACAAGCCGCTATGGTGA
			\FF
			GTACTTCGGCATCAAAAAAGCGTATTCGTAAAAAT........AA................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
			.................................................................................................................................................................................................................................................................................................................................................
			\FE42:\FF
			.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
			.................................................................................................................................................................................................................................................................................................................................................ATTCAAGACAAGCCGCTATGGTGA
			\FF
			</block>
		</matrix>
	</alignment>
</phyde><?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Tue Feb 23 14:01:51 CET 2016  -->
<phyde id="JgfyFmbkEeGK3HRf" version="0.994">
	<description></description>
	<alignment datatype="dna" width="870" height="3" gencode="0" offset="-1">
		<header>
			<entries>
				32 "testNumber" NUMBER
				33 "testFile" FILE
				34 "testString" STRING
			</entries>
			<seq idx="0" cs1="883877" >
				<e id="1">593_cp4243-cp42</e>
				<e id="2">593_cp4243-cp42.scf</e>
			</seq>
			<seq idx="1" cs1="26070374" >
				<e id="1">593_cp4243-cp43</e>
				<e id="2">593_cp4243-cp43.scf</e>
				<e id="32">18</e>
				<e id="33">someFile.txt</e>
				<e id="34">some String</e>
				<e id="3">45</e>
				<e id="4">some Comment</e>
			</seq>
			<seq idx="2" cs1="885853" >
				<e id="1">Melampyrum nemorosum (593 Con) SE</e>
				<e id="4">Consensus: 593_cp4243_42 + 593_cp4243_cp43</e>
			</seq>
		</header>
		<matrix>
			<block x="0" y="0" width="870" height="3">
			\FE53:
			TTTTGGAAaaGGAAGGGATATTGGACAGCGGTAAAAGCGTTTTCTTTAGGTAAATCCCTGTCTACTGGAAATTCAAAAAGTTTTTTGAGCGACAAACAAATAAAATAAGTAAAAAAAATCTTAAAACATAACATGCTGGAATAAGCTAATATAGGCCCGACTCGCTTTTGGAGTAATTTCAGATCAAAAATCCAATTCTCGAATTCCATTTCCTAGTGAGTAACTCAATAGGAAATGGAATTCGTTCTACTATAATAGAATAGAACTTAGAATCAGAATTTTTCTATATTCACTTTCCGCATTAAAAAATTAAGAAACTTTCGTCTTGTTGACAAAAAAAGCAAGATACTCAATTTTTTTTAGTATATTTACGAAATTTACAAGGCGAGGAGTATTATTTTCTCCATCAACCTATTTTATTTGGGATAGACTATAAATTTTATTTTTTGTACAACTTTCTTTCTTTTCTAACCTCGTACCTCGTATATATCAGCATCAATCCACGCAAA
			AAGACTTAGTTAAGATGTTTTCAAATATGTCGAAATTTTGAATGATTCAAAATAGGTTCTTTTTTCAATGATTTTTGTTTCTCTTTTTGAAATCAAATAAATCAAAAACGATTCATTAAAAAAAAAATAAAAAATACACAATAAAACTACGACCCTAGCTTCAAATTCAAATAATGAACCCTCAAATACCTAAGTTGAATGAATTTTTATTTTTGATTCATGAATTTGACTTTTTCCTAAAAAATATTACACCCAATTTCATTCTTAAATCTAGACGGTTGCTTATTCATAGGCTATTATGAATTCAAGACAAGCCGCTATGGTGA
			\FF
			GTACTTCGGCATCAAAAAAGCGTATTCGTAAAAAT........AA................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
			.................................................................................................................................................................................................................................................................................................................................................
			\FE42:\FF
			.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
			.................................................................................................................................................................................................................................................................................................................................................ATTCAAGACAAGCCGCTATGGTGA
			\FF
			</block>
		</matrix>
	</alignment>
</phyde>