<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Wed May 25 15:44:41 CEST 2016  -->
<phyde id="hdARWvE4ZmxCED7C" version="0.994"><description></description>
<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
<header><entries>
</entries>
<seq idx="0" cs1="13355" ><e id="1">C</e>
</seq>
<seq idx="1" cs1="13096" ><e id="1">B</e>
</seq>
<seq idx="2" cs1="13800" ><e id="1">A</e>
<e id="4">some sequence</e>
</seq>
</header>
<matrix><block x="0" y="0" width="20" height="3">
ACGTCGCTCGAG-CTGATCGGGGT
CACGGTG--CTAG.A.....
\FF
TT-ACGATGA.TTG.A
</block>
</matrix></alignment>
</phyde>
