<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Wed May 25 15:44:41 CEST 2016  -->
<phyde id="hdARWvE4ZmxCED7C" version="0.994">
<description></description>
<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
<matrix>
<block x="0" y="0" width="20" height="3">
ACTGACTGACTGTGACCATA
\FF
....................
\FF
....................
\FF
</block>
</matrix>
</alignment>
</phyde>