<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Wed May 25 15:39:08 CEST 2016  -->
<phyde id="6zc8dgxEkB9ErmCn" version="0.994"><description></description>
<alignment datatype="dna" width="23" height="3" gencode="0" offset="-1">
<header><entries>
32 "testNumber" NUMBER
</entries>
<seq idx="0" cs1="17392" ><e id="1">A</e>
<e id="4">some sequence</e>
<e id="2">someFile.scf</e>
</seq>
<seq idx="1" cs1="18076" ><e id="1">B</e>
<e id="2">someFile.scf</e>
<e id="3">45</e>
<e id="4">some comment</e>
<e id="32">18</e>
<e id="33">some String</e>
<e id="34">someFile.txt</e>
</seq>
<seq idx="2" cs1="17612" ><e id="1">C</e>
<e id="2">\\\\\\\\nwz.wwu.de\\\\dfs\\\\home\\\\s\\\\s_wiec03\\\\Desktop\\\\sample.scf</e>
<e id="4">some comment</e>
</seq>
</header>
</alignment>
</phyde>
