<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Wed May 25 15:39:08 CEST 2016  -->
<phyde id="6zc8dgxEkB9ErmCn" version="0.994"><description></description>
<alignment datatype="dna" width="23" height="3" gencode="0" offset="-1">
</alignment>
</phyde>