<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Fri May 27 11:16:07 CEST 2016  -->
<phyde id="AIh7wuZtLeZhUqpV" version="0.994">
<description></description>
<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
<header>
<seq idx="0">
<e id="1">C</e>
</seq>
<seq idx="1">
</seq>
</header>
<matrix>
<block x="0" y="0" width="20" height="3">
ACTGACTGACTGTGACCATA
\FF
....................
\FF
....................
\FF
</block>
</matrix>
</alignment>
</phyde>