<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Tue Feb 23 14:01:51 CET 2016  -->
<phyde id="JgfyFmbkEeGK3HRf" version="0.994">
	<description></description>
	<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
		<header>
			<entries>
				32 "testNumber" NUMBER
				33 "testFile" FILE
				34 "testString" STRING
			</entries>
			<seq idx="0" cs1="883877" >
				<e id="1">sequence1</e>
				<e id="2">someFile.scf</e>
			</seq>
			<seq idx="1" cs1="26070374" >
				<e id="1">sequence2</e>
				<e id="2">someFile.scf</e>
				<e id="32">18</e>
				<e id="33">someFile.txt</e>
				<e id="34">some String</e>
				<e id="3">45</e>
				<e id="4">some Comment</e>
			</seq>
			<seq idx="2" cs1="885853" >
				<e id="1">sequence3</e>
				<e id="4">some comment</e>
			</seq>
		</header>
		<matrix>
			<block x="0" y="0" width="20" height="3">
				ACTGACTGACTGACTGACTG\FF
				ACTGACTGACTGACTGACTG\FF
				ACTGACTGACTGACTGACTG\FF
			</block>
		</matrix>
	</alignment>
</phyde>