<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Mon Feb 03 13:16:06 CET 2014  -->
<phyde id="qMITNoOXTDPvWTBE" version="0.994">
	<description></description>
	<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
		<header>
			<seq idx="0" cs1="23373692" >
				<e id="1">sequence1</e>
			</seq>
			<seq idx="1" cs1="20219626" >
				<e id="1">sequence2</e>
			</seq>
			<seq idx="2" cs1="23381804" >
				<e id="1">sequence3</e>
				<e id="4">Comment</e>
			</seq>
		</header>
		<matrix>
			<block x="0" y="0" width="20" height="3">
				ACTGACTGACTGACTGACTG\FF
				ACTGACTGACTGACTGACTG\FF
				ACTGACTGACTGACTGACTG\FF
			</block>
		</matrix>
	</alignment>
</phyde>