<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Fri May 27 11:16:07 CEST 2016  -->
<phyde id="AIh7wuZtLeZhUqpV" version="0.994"><description></description>
<alignment datatype="dna" width="20" height="3" gencode="0" offset="-1">
<header><seq idx="0"><e id="1">C</e>
<txsets>1</txsets>
</seq>
<seq idx="1"><e id="1">B</e>
</seq>
<seq idx="2"><e id="1">A</e>
<e id="4">some sequence</e>
<txsets>1</txsets>
</seq>
</header>
<TaxonSets>
"taxa1"
</TaxonSets>
<matrix><block x="0" y="0" width="20" height="3">
ACTGACTGACTGTGACCATA
\FF
....................
\FF
....................
\FF
</block>
</matrix></alignment>
</phyde>