<?xml version="1.0" standalone="no"?>
<!-- Generated by PhyDE 0.9971
Mon Feb 03 13:16:06 CET 2014  -->
<phyde id="qMITNoOXTDPvWTBE" version="0.994">
	<description></description>
	<alignment datatype="dna" width="805" height="3" gencode="0" offset="-1">
		<header>
			<seq idx="0" cs1="23373692" >
				<e id="1">591_cp4243-cp42</e>
				<e id="2">2014-01-29/591_cp4243-cp42.scf.gz</e>
			</seq>
			<seq idx="1" cs1="20219626" >
				<e id="1">591_cp4243-cp43</e>
				<e id="2">2013-Okt-Nov/591_cp4243-cp43.scf</e>
			</seq>
			<seq idx="2" cs1="23381804" >
				<e id="1">Euphrasia officnalis rostk. 591 Cons</e>
				<e id="4">Consensus aus cp43:Okt-Nov13,cp42 29.01.14 </e>
			</seq>
		</header>
		<matrix>
			<block x="0" y="0" width="805" height="3">
				TTTTGGAAAGGAGGGGGTATTGGACAGCATTAAAAGCGCTTTCCTTAGGTAAATCTCTTTCTACCGGAAATTCAAAAAGTTTTTTGAGCGACAAACAAATAAAATAAGTAAAAAAAAATATTAAAACATAACATGTTTGAATAATCTAAATAGACTCGACTCACTTTTTTGAAGTCATTTCCTATCAAATATAAAATCCAAATTATCGAATTCCATTTCGTAGTGAGTAACACTACGAAATGGAATTCGATAATTTGGATTTTAGAATAGAATTTAGAATAAGAATTTTTCTATATTACCTTTCCGAATTAAAAATAAAAAGAAAAGACGTCCGTCTTGTTGACAAAAAAAAAGATACTAAATTTTAGTTTTTGTCTAACTTTCTTTCTTTGCTAATCTACTATATAGACCCCTTCTAGATATATCAGCATTAATCTACGCAAAACTACTTACTTAGTTAAGGTGTTTTCTGAATAAATATGTGGAAATTTTAAATAAGTCAAAAAGGC
				AAACAGCCTTTTTTTTGAGGCGATTCTAACCCATAGACTGTATGGTTTTACAAAAAAAGTGCAAATCACGATAAAGTAGTAATAGAAAATACACAATAAAATTATGACCCTAGCCGGAAATTAAAATAATGAACCTTCAAATACCTAAAATTTTTATTCATCAATTTGAATATTTCCTAAAAACTATTACACCCGATTTCATTCTTAAATCTAGACGATTGCTTATTCATAGGCTATTATGAATCCAAGACAAGCCGCTATGGTGAAATTGGTAGACACGCTGCTCTTAAGGAAGC
				\FF
				\FE66:
				.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
				.................................................T...........................................................................................................................
				\FE75:\FF
				TTTTGGAAAGGAGGGGGTATTGGACAGCATTAAAAGCGCTTTCCTTAGGTAAATCTCTTTCTACCG...........................................................................................................................................................................................................................................................................................................................................................................................................................................................
				...............................................................................................................................................................................................................................................TGAATCCAAGACAAGCCGCTATGGTGAAATTGGTAGACACGCTGCTCTTAAGGAAGC
				\FF
			</block>
		</matrix>
	</alignment>
</phyde>